### ISSUE TITLE
Ide gas

### ISSUE THREAD

**Issue by deyyanl** [Minlor/Aivo-Async#1]
dodaj a!idegas da ti generise ide gas gif ili ide neon svedno xd

**Comment by Minlor** [comment]
Može može, dodaje se u novom update :)

-------- Original Message --------

**Comment by ChineseMarc** [comment]
#2

**Comment by ChineseMarc** [comment]
aloe gaseri ocemo li ovo?

**Comment by deyyanl** [comment]
Gahahahahah

**Comment by deyyanl** [comment]
Minljore

**Comment by Minlor** [comment]
Oce al bit ce u novom botu ovo je stara verzija bota za novu gledaj https://github.com/Minlor/Aivo xD
